#!/bin/bash

description=$@
user="wakeful-deployment"
repo="consul-join"
tag=v$(cat VERSION)
sha=""

echo "Preparing release for ${tag}..."

go build consul-join.go

if [[ $? != "0" ]]; then
  echo "Failed to compile"
  exit 1
fi

go test ./...

if [[ $? != "0" ]]; then
  echo "Tests failed"
  exit 1
fi

found_tag=$(git tag -l $tag | wc -l)

if [[ $found_tag != "1" ]]; then
  echo "You need to tag this release and push:"
  echo "$ git tag $tag"
  echo "$ git push --tags"
  exit 1
fi

zip consul-join-x86-linux.zip consul-join

sha=$(sha256sum -b consul-join-x86-linux.zip | awk '{ print $1 }')
echo SHA256 $sha
description="$description
SHA256: \`$sha\`"
echo Description: $description

github-release info -u $user -r $repo -t $tag | grep -q "\- $tag, name:"

if [[ $? != 0 ]]; then
  echo "Pushing release to github..."
  github-release release -u $user -r $repo -t $tag -d "$description"
fi

github-release info -u $user -r $repo -t $tag | grep -q "\- artifact: consul-join"

if [[ $? = "0" ]]; then
  echo "There is already a file uploaded, please remove to replace with new zip file"
  exit 1
else
  echo "Uploading the compiled binary..."
  github-release upload -u $user -r $repo -t $tag -f consul-join-x86-linux.zip -n consul-join-x86-linux.zip
fi
