#!/bin/bash

description=$@
tag=v$(cat VERSION)
tagfound=$(git tag -l $tag | wc -l | tr -d ' ')

if [[ "$tagfound" != "1" ]]; then
  echo "Tagging ${tag}..."
  git tag $tag
  git push --tags
fi

which docker-machine

if [[ $? = "0" ]]; then
  eval $(docker-machine env default)
fi

docker build -t consul-join-release .
docker ps -a --format "{{.Names}} {{.ID}}" | grep consul-join-release | awk '{ print $2 }' | xargs docker rm
docker run -it -e GITHUB_TOKEN=$GITHUB_TOKEN --name consul-join-release consul-join-release ./release $description
